# Generated by Django 3.0.4 on 2020-04-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='profile_picture',
            field=models.ImageField(default='employee.jpg', upload_to='employees'),
        ),
    ]
