# Generated by Django 3.0.4 on 2020-07-13 06:14

from django.db import migrations, models
import job_seeker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0005_auto_20200419_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumes',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes', validators=[job_seeker.validators.validate_file_extension]),
        ),
    ]
