# Generated by Django 3.0.4 on 2020-07-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_auto_20200713_1241'),
        ('job_seeker', '0007_examresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('job', 'employee')},
        ),
    ]
