# Generated by Django 3.0.4 on 2020-07-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0008_auto_20200713_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='attend_exam',
            field=models.BooleanField(default=False),
        ),
    ]
