# Generated by Django 3.0.4 on 2020-04-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='A Detailed Description about Employer')),
                ('location', models.CharField(help_text='Employer location', max_length=150)),
                ('address', models.TextField(blank=True, help_text='Detaild address', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=50)),
                ('description', models.TextField(help_text='A Detailed Description about job')),
                ('qualifications', models.CharField(max_length=150)),
                ('experience', models.IntegerField(default='0', help_text='Minimum experience')),
                ('salary', models.CharField(default='Salary package is not provided', help_text='Default currency is INR ₹', max_length=15)),
                ('location', models.CharField(help_text='Job location', max_length=150)),
                ('type', models.CharField(choices=[('full time', 'Full time'), ('part time', 'Part time'), ('internship', 'Internship')], max_length=50)),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employer.Employer')),
            ],
        ),
    ]
