# Generated by Django 3.0.4 on 2020-07-23 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Employer location', max_length=150)),
                ('address', models.TextField(blank=True, help_text='Detaild address', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=50)),
                ('description', models.TextField(help_text='A Detailed Description about job')),
                ('qualifications', models.CharField(max_length=150)),
                ('experience', models.IntegerField(default='0', help_text='Minimum experience')),
                ('salary', models.CharField(blank=True, default='0.00', help_text='Default currency is INR ₹', max_length=15, null=True)),
                ('location', models.CharField(help_text='Job location', max_length=150)),
                ('type', models.CharField(choices=[('full time', 'Full time'), ('part time', 'Part time'), ('internship', 'Internship')], max_length=50)),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('is_opened', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employer.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='OpenedExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('is_questions_finished', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openedExams', to='employer.Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examQuestion', to='employer.Jobs')),
            ],
        ),
    ]
