# Generated by Django 3.0.4 on 2020-04-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='A Detailed Description about Company')),
                ('location', models.CharField(help_text='Company location', max_length=150)),
                ('email', models.EmailField(error_messages={'required': 'Please provide email', 'unique': 'This email address is taken'}, max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Contact number', max_length=12, unique=True)),
                ('address', models.TextField(blank=True, help_text='Detaild address', null=True)),
                ('about', models.TextField(blank=True, help_text='About Company', null=True)),
                ('logo', models.ImageField(default='company_default.jpg', upload_to='company')),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=50)),
                ('description', models.TextField(help_text='A Detailed Description about job')),
                ('qualifications', models.CharField(max_length=150)),
                ('experience', models.IntegerField(default='0', help_text='Minimum experience')),
                ('salary', models.CharField(default='Salary package is not provided', help_text='Default currency is INR ₹', max_length=15)),
                ('location', models.CharField(help_text='Job location', max_length=150)),
                ('working_time', models.CharField(default='Full time', max_length=50)),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employer.Company')),
            ],
        ),
    ]
