# Generated by Django 3.0.4 on 2020-04-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='A Detailed Description about Employer')),
                ('location', models.CharField(help_text='Employer location', max_length=150)),
                ('email', models.EmailField(error_messages={'required': 'Please provide email', 'unique': 'This email address is taken'}, max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Contact number', max_length=12, unique=True)),
                ('address', models.TextField(blank=True, help_text='Detaild address', null=True)),
                ('about', models.TextField(blank=True, help_text='About Employer', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobs',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employer.Employer'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
