# Generated by Django 3.0.4 on 2020-07-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_employer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='option4',
        ),
    ]
