# Generated by Django 3.0.4 on 2020-04-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20200416_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='description',
        ),
    ]
