# Generated by Django 3.0.4 on 2020-07-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_employer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
