# Generated by Django 3.0.4 on 2020-07-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_examquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='job_expiry',
            new_name='is_opened',
        ),
    ]
