# Generated by Django 3.0.4 on 2020-07-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_auto_20200714_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenedExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openedExams', to='employer.Jobs')),
            ],
        ),
    ]
