# Generated by Django 3.0.4 on 2020-07-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_auto_20200721_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedexams',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
