# Generated by Django 3.0.4 on 2020-07-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_auto_20200721_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedexams',
            name='is_questions_finished',
            field=models.BooleanField(default=False),
        ),
    ]
